name: gromartconsumer
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bluetooth_thermal_printer: ^0.0.6
  cached_network_image: ^3.2.1
  clipboard: ^0.1.3
  cloud_firestore: ^3.4.1
  cupertino_icons: ^1.0.4
  dotted_border: ^2.0.0+2
  easy_localization: ^3.0.2-dev
  esc_pos_utils: ^1.1.0
  firebase_auth: ^3.3.19
  firebase_core: ^1.20.0
  firebase_crashlytics: ^2.8.3
  firebase_messaging: ^11.4.1
  firebase_storage: ^10.2.17
  flutter:
    sdk: flutter
  flutter_braintree: null
  flutter_facebook_auth: ^4.3.4
  flutter_facebook_keyhash: ^0.0.4
  flutter_native_image: ^0.0.6+1
  flutter_polyline_points: ^1.0.0
  flutter_qr_bar_scanner: ^3.0.2
  flutter_rating_bar: ^4.0.1
  flutter_sound: ^8.3.9
  flutter_staggered_grid_view: ^0.4.1
  flutter_stripe: ^3.0.2
  flutterwave_standard: ^1.0.3
  font_awesome_flutter: ^10.1.0
  geocoding: ^2.0.4
  geoflutterfire: ^3.0.3
  geolocator: ^7.0.1
  google_maps_flutter: null
  http: ^0.13.4
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  intl_phone_number_input: ^0.7.0+2
  location: ^4.4.0
  lottie: ^1.3.0
  mercadopago_sdk: ^1.3.0
  moor_flutter: ^4.1.0
  path_provider: ^2.0.10
  paytm_allinonesdk: ^1.1.7
  percent_indicator: ^4.2.2
  permission_handler: ^6.0.1+1
  photo_view: ^0.14.0
  pin_code_fields: ^7.4.0
  place_picker: ^0.9.19
  progress_dialog:
    git:
      url: https://github.com/mostafaAbdelazim/progress_dialog.git
  razorpay_flutter: ^1.3.2
  rename: ^2.0.1
  share: ^2.0.4
  shared_preferences: ^2.0.15
  smooth_page_indicator: ^1.0.0+2
  the_apple_sign_in: ^1.1.1
  url_launcher: ^6.1.2
  uuid: ^3.0.6
  video_compress: ^3.1.0
  video_player: ^2.4.2
  video_thumbnail: ^0.5.0
  webview_flutter: ^3.0.4
  pdf: ^3.8.4
  open_file: ^3.2.1


dev_dependencies:
  build_runner: ^2.0.6
  flutter_launcher_icons: ^0.9.1
  moor_generator: ^4.4.1
  flutter_native_splash: ^2.2.13

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: 'assets/images/GroShop-app-icon.png'

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/GroShop-app-icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
    - assets/fonts/
    - assets/flags/

  fonts:
    - family: Poppinsb
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: Poppinsl
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf

    - family: Poppinsm
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: Poppinsr
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: Poppinssb
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
